j178/leetgo

cmd/inspect.go, cmd/root.go, leetcode/client.go
- Add inspect command
- Hide inspect
- Minor
=> Add inspect developer command

README.md, README_zh.md, cmd/contest.go, cmd/test.go, config/config.go, go.mod, go.sum, lang/gen.go, lang/go.go, leetcode/client.go, leetcode/client_us.go, leetcode/contest.go, leetcode/decoder.go, leetcode/qid.go, leetcode/question.go, utils/str.go
- Basic contest info
- Add register and unregister
=> Support contest

cmd/root.go, config/config.go
=> Improve config invalid error report

README.md, README_en.md, cmd/info.go, cmd/root.go, config/config.go, leetcode/client.go, leetcode/client_us.go, leetcode/contest.go, leetcode/credential.go, leetcode/qid.go, leetcode/question.go, misc/leetcode-cn-Query.json
=> feat: add us api

editor/editor.go, editor/vim.go, leetcode/cache_sqlite.go
Add neovim editor support #60.
This will be a Draft PR until the previous fix PR #95 is merged.
=> feat: support neovim

cmd/contest.go, cmd/debug.go, cmd/submit.go, cmd/test.go, leetcode/models.go
=> feat: reduce wait time for premium user

cmd/contest.go, config/config.go, leetcode/client_us.go
- fix: improve us top-two contest fetch
- fix started contest time format
=> fix: improve us top-two contest fetch

go.mod, go.sum, leetcode/client.go
=> feat: add retry on 503

go.mod, go.sum
=> feat: bump kooky to include support of chromium-based Edge on macOS

.github/workflows/ci.yaml, go.mod
=> feat: upgrade to go1.20

config/config.go, lang/base.go
per https://github.com/j178/leetgo/issues/112#issuecomment-1453440626
=>  feat: add getTempBinFile

lang/cpp.go, testutils/cpp/LC_IO.h
Revert #141, use a simpler approach mentioned in #138.
=> fix: don't include <bits/stdc++.h> if not using gcc

.goreleaser.yaml, cmd/init.go, cmd/root.go, config/config.go, config/encrypt.go, constants/constants.go, editor/editor.go, lang/base.go, lang/cpp.go, lang/gen.go, lang/go.go, lang/version.go, testutils/cpp/header.go, utils/file.go
=> feat: add version to directly embed language libraries

README.md, README_zh.md, leetcode/client.go, leetcode/qid.go
=> feat: support `yesterday`, `today-1` to retrieve passed everyday questions

cmd/submit.go, lang/test.go, leetcode/models.go
=> feat: append failed case to testcases.txt after submitting

README.md, README_zh.md, cmd/root.go, config/config.go
=> feat: support --site flag

go.mod, go.sum, lang/go.go, lang/judge.go, lang/test.go, leetcode/question.go
=> feat: implement basic slice comparison ignoring order

cmd/test.go, lang/base.go, lang/cpp.go, lang/go.go, lang/python.go, lang/range_test.go, lang/rust.go, lang/test.go
```
leetgo test -t 1      # run first case only
leetgo test -t -1     # run last case only
leetgo test -t 1,3    # run first and third case
leetgo test -t 1,3-5  # run first, thrid, forth and fifth case
```
=> feat: support flexible target case parameter

README.md, README_zh.md, lang/list.go
Submits tested with these code
https://github.com/seognil/leetgo/tree/test/test/solutions
=> feat: update supported langs

leetcode/credential.go
=> feat: show cookies loading error

cmd/root.go, cmd/submit.go, cmd/test.go
=> feat: error exit if test or submit failure

leetcode/models.go, utils/str.go
=> feat: truncate too long test case

lang/rust.go
Only parse `[bin]` section, retains all other values, keeps future compatibility.
Fixes #249
=> fix: support future cargo.toml

lang/python.go, lang/test.go, testutils/python/pyproject.toml, testutils/python/src/leetgo_py/parse.py
=> fix: serialize `None` according to return type

.github/workflows/release.yaml, .goreleaser.yaml, README.md, README_zh.md
=> feat: add archlinux user repository installation

lang/rust.go
=> fix(rust): pick question panic when there is no bin in Cargo.toml

lang/base.go
=> fix: ignore invalid testcase output

README.md, README_zh.md, config/config.go, leetcode/credential.go
- feat: `leetcode.credentials.from` supports multiple sources
- Add doc
=> feat: support specifiying multiple credential sources
